# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: 0.71
  joint_a2: 1.54
  joint_a3: 0.92
  joint_a4: 1.39
  joint_a5: 2.5
  joint_a6: 1.74
  joint_a7: -1.20
